
postgres:
  database: ibit_task
  user: ibit_task_admin
  password: mewlDap=hispit9lCHiP
  host: localhost
  port: 5432

logger:
  stream: True
  file_name: crypto_api.log
  level: 20
  # (reminder) Log Levels
  # CRITICAL - 50
  # ERROR    - 40
  # WARNING  - 30
  # INFO     - 20
  # DEBUG    - 10
  # NOTSET   - 0
