
postgres:
  database: ibit_task
  user: ibit_task_admin
  password: mewlDap=hispit9lCHiP
  host: localhost
  port: 5432

ethereum:
  chainId: 4224
  IPCProvider: /home/alexk/PycharmProjects/Ibit_task/ETH/geth.ipc
  gas: 900000


ethereum_url:
  IP: 127.0.0.1
  port: 8545

logger:
  stream: True
  file_name: crypto_api.log
  level: 20
  # Log Levels (reminder)
  # CRITICAL - 50
  # ERROR    - 40
  # WARNING  - 30
  # INFO     - 20
  # DEBUG    - 10
  # NOTSET   - 0
